/**
 * Shape Shift Puzzle Database
 *
 * REWRITTEN V4:
 * - Grid: 100x100 design units.
 * - Designs: recognizable assemblies using square and rectangular footprints.
 * - Coordinates: Top-Left based. Center of grid is 50,50.
 */

import type { ContentPack } from '../../types';
import { MATH_GEOMETRY_SHAPES_SKILL } from '../../skills/math';
import type { Puzzle } from '../../../types/game';

export const SHAPE_SHIFT_PUZZLES: Puzzle[] = [
  // ============ EASY (Basic Shapes & Simple Objects) ============
  {
    id: 'square_split',
    nameEt: 'Ruut',
    nameEn: 'Square',
    category: 'shapes',
    difficulty: 'easy',
    gridSize: 100,
    pieces: [
      // Two right triangles forming a square (Tangram style)
      // Top-Left Half
      {
        id: 'p1',
        type: 'half_square',
        color: 'blue',
        correctPosition: { x: 30, y: 30 },
        correctRotation: 0,
        size: 40,
      },
      // Bottom-Right Half
      {
        id: 'p2',
        type: 'half_square',
        color: 'cyan',
        correctPosition: { x: 30, y: 30 },
        correctRotation: 180,
        size: 40,
      },
    ],
  },
  {
    id: 'house_simple',
    nameEt: 'Maja',
    nameEn: 'House',
    category: 'objects',
    difficulty: 'easy',
    gridSize: 100,
    pieces: [
      // Roof (Overhangs slightly)
      {
        id: 'roof',
        type: 'triangle',
        color: 'red',
        correctPosition: { x: 25, y: 15 },
        correctRotation: 0,
        size: 50,
      },
      // Body
      {
        id: 'walls',
        type: 'square',
        color: 'white',
        correctPosition: { x: 35, y: 50 },
        correctRotation: 0,
        size: 30,
      },
    ],
  },
  {
    id: 'tree_simple',
    nameEt: 'Puu',
    nameEn: 'Tree',
    category: 'objects',
    difficulty: 'easy',
    gridSize: 100,
    pieces: [
      // Foliage
      {
        id: 'top',
        type: 'triangle',
        color: 'green',
        correctPosition: { x: 25, y: 10 },
        correctRotation: 0,
        size: 50,
      },
      // Trunk
      {
        id: 'trunk',
        type: 'rectangle',
        color: 'brown',
        correctPosition: { x: 44, y: 52 },
        correctRotation: 0,
        size: 32,
        width: 12,
        height: 32,
      },
    ],
  },
  {
    id: 'sun',
    nameEt: 'Päike',
    nameEn: 'Sun',
    category: 'objects',
    difficulty: 'easy',
    gridSize: 100,
    pieces: [
      // Center
      {
        id: 'core',
        type: 'circle',
        color: 'yellow',
        correctPosition: { x: 35, y: 35 },
        correctRotation: 0,
        size: 30,
      },
      // Rays (Cardinals)
      {
        id: 'r_top',
        type: 'triangle',
        color: 'orange',
        correctPosition: { x: 40, y: 10 },
        correctRotation: 0,
        size: 20,
      },
      {
        id: 'r_bottom',
        type: 'triangle',
        color: 'orange',
        correctPosition: { x: 40, y: 70 },
        correctRotation: 180,
        size: 20,
      },
      {
        id: 'r_left',
        type: 'triangle',
        color: 'orange',
        correctPosition: { x: 10, y: 40 },
        correctRotation: 270,
        size: 20,
      },
      {
        id: 'r_right',
        type: 'triangle',
        color: 'orange',
        correctPosition: { x: 70, y: 40 },
        correctRotation: 90,
        size: 20,
      },
    ],
  },
  {
    id: 'candy',
    nameEt: 'Komm',
    nameEn: 'Candy',
    category: 'objects',
    difficulty: 'easy',
    gridSize: 100,
    pieces: [
      // Center
      {
        id: 'pop',
        type: 'circle',
        color: 'pink',
        correctPosition: { x: 35, y: 35 },
        correctRotation: 0,
        size: 30,
      },
      // Wrapper Ends
      {
        id: 'w_left',
        type: 'triangle',
        color: 'purple',
        correctPosition: { x: 10, y: 35 },
        correctRotation: 90,
        size: 25,
      },
      {
        id: 'w_right',
        type: 'triangle',
        color: 'purple',
        correctPosition: { x: 65, y: 35 },
        correctRotation: 270,
        size: 25,
      },
    ],
  },
  {
    id: 'balloon',
    nameEt: 'Õhupall',
    nameEn: 'Balloon',
    category: 'objects',
    difficulty: 'easy',
    gridSize: 100,
    pieces: [
      {
        id: 'balloon',
        type: 'circle',
        color: 'red',
        correctPosition: { x: 32, y: 12 },
        correctRotation: 0,
        size: 36,
      },
      {
        id: 'knot',
        type: 'triangle',
        color: 'red',
        correctPosition: { x: 43, y: 46 },
        correctRotation: 180,
        size: 14,
      },
      {
        id: 'string',
        type: 'rectangle',
        color: 'gray',
        correctPosition: { x: 48, y: 60 },
        correctRotation: 0,
        size: 30,
        width: 4,
        height: 30,
      },
    ],
  },
  {
    id: 'mushroom',
    nameEt: 'Seen',
    nameEn: 'Mushroom',
    category: 'objects',
    difficulty: 'easy',
    gridSize: 100,
    pieces: [
      {
        id: 'cap',
        type: 'circle',
        color: 'red',
        correctPosition: { x: 25, y: 18 },
        correctRotation: 0,
        size: 50,
      },
      {
        id: 'stem',
        type: 'rectangle',
        color: 'white',
        correctPosition: { x: 42, y: 56 },
        correctRotation: 0,
        size: 30,
        width: 16,
        height: 30,
      },
      {
        id: 'spot_left',
        type: 'circle',
        color: 'white',
        correctPosition: { x: 36, y: 30 },
        correctRotation: 0,
        size: 10,
      },
      {
        id: 'spot_right',
        type: 'circle',
        color: 'white',
        correctPosition: { x: 54, y: 30 },
        correctRotation: 0,
        size: 10,
      },
    ],
  },

  // ============ MEDIUM (Animals & Transport) ============
  {
    id: 'boat_sleek',
    nameEt: 'Paat',
    nameEn: 'Boat',
    category: 'objects',
    difficulty: 'medium',
    gridSize: 100,
    pieces: [
      // Wide hull at the bottom
      {
        id: 'hull_main',
        type: 'rectangle',
        color: 'brown',
        correctPosition: { x: 10, y: 72 },
        correctRotation: 0,
        size: 80,
        width: 80,
        height: 18,
      },
      // Mast
      {
        id: 'mast',
        type: 'rectangle',
        color: 'gray',
        correctPosition: { x: 46, y: 30 },
        correctRotation: 0,
        size: 44,
        width: 8,
        height: 44,
      },
      // Sail pointing right, attached to mast
      {
        id: 'sail_main',
        type: 'triangle',
        color: 'white',
        correctPosition: { x: 54, y: 20 },
        correctRotation: 90,
        size: 40,
      },
    ],
  },
  {
    id: 'fish_gold',
    nameEt: 'Kuldne Kala',
    nameEn: 'Goldfish',
    category: 'animals',
    difficulty: 'medium',
    gridSize: 100,
    pieces: [
      // Body (Circle) - Center 50,50. Radius 25. x=25..75
      {
        id: 'body',
        type: 'circle',
        color: 'gold',
        correctPosition: { x: 25, y: 25 },
        correctRotation: 0,
        size: 50,
      },
      // Tail (Triangle pointing right) - Base attached to body at x=75.
      // Rot 90 base is at x=75 (Left of box).
      {
        id: 'tail',
        type: 'triangle',
        color: 'orange',
        correctPosition: { x: 5, y: 35 },
        correctRotation: 270,
        size: 30,
      },
      {
        id: 'eye',
        type: 'circle',
        color: 'white',
        correctPosition: { x: 60, y: 38 },
        correctRotation: 0,
        size: 8,
      },
    ],
  },
  {
    id: 'cat_face',
    nameEt: 'Kass',
    nameEn: 'Cat',
    category: 'animals',
    difficulty: 'medium',
    gridSize: 100,
    pieces: [
      {
        id: 'head',
        type: 'circle',
        color: 'gray',
        correctPosition: { x: 25, y: 25 },
        correctRotation: 0,
        size: 50,
      },
      {
        id: 'ear_l',
        type: 'triangle',
        color: 'gray',
        correctPosition: { x: 20, y: 5 },
        correctRotation: 0,
        size: 25,
      },
      {
        id: 'ear_r',
        type: 'triangle',
        color: 'gray',
        correctPosition: { x: 55, y: 5 },
        correctRotation: 0,
        size: 25,
      },
      {
        id: 'eye_l',
        type: 'circle',
        color: 'cyan',
        correctPosition: { x: 38, y: 42 },
        correctRotation: 0,
        size: 8,
      },
      {
        id: 'eye_r',
        type: 'circle',
        color: 'cyan',
        correctPosition: { x: 54, y: 42 },
        correctRotation: 0,
        size: 8,
      },
      {
        id: 'nose',
        type: 'diamond',
        color: 'pink',
        correctPosition: { x: 46, y: 52 },
        correctRotation: 0,
        size: 8,
      },
    ],
  },
  {
    id: 'rocket',
    nameEt: 'Rakett',
    nameEn: 'Rocket',
    category: 'objects',
    difficulty: 'medium',
    gridSize: 100,
    pieces: [
      {
        id: 'nose',
        type: 'triangle',
        color: 'red',
        correctPosition: { x: 36, y: 8 },
        correctRotation: 0,
        size: 28,
      },
      {
        id: 'body',
        type: 'rectangle',
        color: 'white',
        correctPosition: { x: 39, y: 34 },
        correctRotation: 0,
        size: 44,
        width: 22,
        height: 44,
      },
      {
        id: 'window',
        type: 'circle',
        color: 'cyan',
        correctPosition: { x: 45, y: 44 },
        correctRotation: 0,
        size: 10,
      },
      // Fins
      {
        id: 'fin_l',
        type: 'triangle',
        color: 'red',
        correctPosition: { x: 20, y: 62 },
        correctRotation: 270,
        size: 24,
      },
      {
        id: 'fin_r',
        type: 'triangle',
        color: 'red',
        correctPosition: { x: 56, y: 62 },
        correctRotation: 90,
        size: 24,
      },
      {
        id: 'flame',
        type: 'triangle',
        color: 'orange',
        correctPosition: { x: 41, y: 76 },
        correctRotation: 180,
        size: 18,
      },
    ],
  },
  {
    id: 'butterfly',
    nameEt: 'Liblikas',
    nameEn: 'Butterfly',
    category: 'animals',
    difficulty: 'medium',
    gridSize: 100,
    pieces: [
      {
        id: 'body',
        type: 'rectangle',
        color: 'gray',
        correctPosition: { x: 46, y: 28 },
        correctRotation: 0,
        size: 44,
        width: 8,
        height: 44,
      },
      {
        id: 'upper_left_wing',
        type: 'circle',
        color: 'pink',
        correctPosition: { x: 18, y: 20 },
        correctRotation: 0,
        size: 36,
        width: 30,
        height: 38,
      },
      {
        id: 'upper_right_wing',
        type: 'circle',
        color: 'pink',
        correctPosition: { x: 52, y: 20 },
        correctRotation: 0,
        size: 36,
        width: 30,
        height: 38,
      },
      {
        id: 'lower_left_wing',
        type: 'circle',
        color: 'purple',
        correctPosition: { x: 24, y: 54 },
        correctRotation: 0,
        size: 26,
        width: 24,
        height: 26,
      },
      {
        id: 'lower_right_wing',
        type: 'circle',
        color: 'purple',
        correctPosition: { x: 52, y: 54 },
        correctRotation: 0,
        size: 26,
        width: 24,
        height: 26,
      },
      {
        id: 'head',
        type: 'circle',
        color: 'gray',
        correctPosition: { x: 43, y: 16 },
        correctRotation: 0,
        size: 14,
      },
    ],
  },
  {
    id: 'sword',
    nameEt: 'Mõõk',
    nameEn: 'Sword',
    category: 'objects',
    difficulty: 'medium',
    gridSize: 100,
    pieces: [
      // Tip
      {
        id: 'blade_tip',
        type: 'triangle',
        color: 'white',
        correctPosition: { x: 40, y: 2 },
        correctRotation: 0,
        size: 20,
      },
      // Blade
      {
        id: 'blade',
        type: 'rectangle',
        color: 'white',
        correctPosition: { x: 44, y: 20 },
        correctRotation: 0,
        size: 52,
        width: 12,
        height: 52,
      },
      // Guard crossbar
      {
        id: 'guard',
        type: 'rectangle',
        color: 'gold',
        correctPosition: { x: 23, y: 70 },
        correctRotation: 0,
        size: 54,
        width: 54,
        height: 8,
      },
      // Hilt below guard, centered at bottom
      {
        id: 'hilt',
        type: 'rectangle',
        color: 'brown',
        correctPosition: { x: 44, y: 78 },
        correctRotation: 0,
        size: 18,
        width: 12,
        height: 18,
      },
      {
        id: 'pommel',
        type: 'circle',
        color: 'gold',
        correctPosition: { x: 42, y: 84 },
        correctRotation: 0,
        size: 16,
      },
    ],
  },
  {
    id: 'car_compact',
    nameEt: 'Auto',
    nameEn: 'Car',
    category: 'objects',
    difficulty: 'medium',
    gridSize: 100,
    pieces: [
      {
        id: 'body',
        type: 'rectangle',
        color: 'blue',
        correctPosition: { x: 18, y: 48 },
        correctRotation: 0,
        size: 64,
        width: 64,
        height: 24,
      },
      {
        id: 'cabin',
        type: 'rectangle',
        color: 'cyan',
        correctPosition: { x: 34, y: 30 },
        correctRotation: 0,
        size: 34,
        width: 34,
        height: 20,
      },
      {
        id: 'wheel_l',
        type: 'circle',
        color: 'gray',
        correctPosition: { x: 26, y: 66 },
        correctRotation: 0,
        size: 16,
      },
      {
        id: 'wheel_r',
        type: 'circle',
        color: 'gray',
        correctPosition: { x: 58, y: 66 },
        correctRotation: 0,
        size: 16,
      },
      {
        id: 'light',
        type: 'circle',
        color: 'yellow',
        correctPosition: { x: 76, y: 54 },
        correctRotation: 0,
        size: 8,
      },
    ],
  },
  {
    id: 'bird_simple',
    nameEt: 'Lind',
    nameEn: 'Bird',
    category: 'animals',
    difficulty: 'medium',
    gridSize: 100,
    pieces: [
      {
        id: 'body',
        type: 'circle',
        color: 'blue',
        correctPosition: { x: 28, y: 34 },
        correctRotation: 0,
        size: 38,
      },
      {
        id: 'head',
        type: 'circle',
        color: 'cyan',
        correctPosition: { x: 58, y: 24 },
        correctRotation: 0,
        size: 24,
      },
      {
        id: 'wing',
        type: 'triangle',
        color: 'purple',
        correctPosition: { x: 30, y: 42 },
        correctRotation: 90,
        size: 22,
      },
      {
        id: 'beak',
        type: 'triangle',
        color: 'orange',
        correctPosition: { x: 78, y: 32 },
        correctRotation: 90,
        size: 16,
      },
      {
        id: 'eye',
        type: 'circle',
        color: 'white',
        correctPosition: { x: 68, y: 31 },
        correctRotation: 0,
        size: 6,
      },
    ],
  },

  // ============ HARD (Premium & Complex) ============
  {
    id: 'crown',
    nameEt: 'Kroon',
    nameEn: 'Crown',
    category: 'objects',
    difficulty: 'hard',
    gridSize: 100,
    pieces: [
      // Base
      {
        id: 'base',
        type: 'rectangle',
        color: 'gold',
        correctPosition: { x: 19, y: 60 },
        correctRotation: 0,
        size: 62,
        width: 62,
        height: 18,
      },
      // Points
      {
        id: 'p_left',
        type: 'triangle',
        color: 'gold',
        correctPosition: { x: 20, y: 30 },
        correctRotation: 0,
        size: 30,
      },
      {
        id: 'p_mid',
        type: 'diamond',
        color: 'red',
        correctPosition: { x: 35, y: 15 },
        correctRotation: 0,
        size: 30,
      },
      {
        id: 'p_right',
        type: 'triangle',
        color: 'gold',
        correctPosition: { x: 50, y: 30 },
        correctRotation: 0,
        size: 30,
      },
    ],
  },
  {
    id: 'castle',
    nameEt: 'Loss',
    nameEn: 'Castle',
    category: 'objects',
    difficulty: 'hard',
    gridSize: 100,
    pieces: [
      {
        id: 'wall',
        type: 'rectangle',
        color: 'gray',
        correctPosition: { x: 24, y: 50 },
        correctRotation: 0,
        size: 52,
        width: 52,
        height: 28,
      },
      {
        id: 'tower_l',
        type: 'rectangle',
        color: 'gray',
        correctPosition: { x: 12, y: 38 },
        correctRotation: 0,
        size: 42,
        width: 18,
        height: 42,
      },
      {
        id: 'tower_r',
        type: 'rectangle',
        color: 'gray',
        correctPosition: { x: 70, y: 38 },
        correctRotation: 0,
        size: 42,
        width: 18,
        height: 42,
      },
      {
        id: 'roof_l',
        type: 'triangle',
        color: 'red',
        correctPosition: { x: 9, y: 20 },
        correctRotation: 0,
        size: 24,
      },
      {
        id: 'roof_r',
        type: 'triangle',
        color: 'red',
        correctPosition: { x: 67, y: 20 },
        correctRotation: 0,
        size: 24,
      },
      {
        id: 'gate',
        type: 'rectangle',
        color: 'brown',
        correctPosition: { x: 43, y: 60 },
        correctRotation: 0,
        size: 18,
        width: 14,
        height: 18,
      },
      {
        id: 'flag',
        type: 'triangle',
        color: 'yellow',
        correctPosition: { x: 45, y: 18 },
        correctRotation: 90,
        size: 18,
      },
    ],
  },
  {
    id: 'gem_cluster',
    nameEt: 'Juveel',
    nameEn: 'Gem',
    category: 'objects',
    difficulty: 'hard',
    gridSize: 100,
    pieces: [
      // Center
      {
        id: 'center',
        type: 'hexagon',
        color: 'cyan',
        correctPosition: { x: 35, y: 35 },
        correctRotation: 0,
        size: 30,
      },
      // Facets
      {
        id: 'f1',
        type: 'triangle',
        color: 'blue',
        correctPosition: { x: 35, y: 10 },
        correctRotation: 0,
        size: 20,
      },
      {
        id: 'f2',
        type: 'triangle',
        color: 'blue',
        correctPosition: { x: 60, y: 30 },
        correctRotation: 90,
        size: 20,
      },
      {
        id: 'f3',
        type: 'triangle',
        color: 'blue',
        correctPosition: { x: 40, y: 65 },
        correctRotation: 180,
        size: 20,
      },
      {
        id: 'f4',
        type: 'triangle',
        color: 'blue',
        correctPosition: { x: 15, y: 40 },
        correctRotation: 270,
        size: 20,
      },
    ],
  },
  {
    id: 'laptop',
    nameEt: 'Sülearvuti',
    nameEn: 'Laptop',
    category: 'objects',
    difficulty: 'hard',
    gridSize: 100,
    pieces: [
      // Screen
      {
        id: 'screen',
        type: 'rectangle',
        color: 'gray',
        correctPosition: { x: 22, y: 20 },
        correctRotation: 0,
        size: 56,
        width: 56,
        height: 36,
      },
      {
        id: 'display',
        type: 'rectangle',
        color: 'cyan',
        correctPosition: { x: 28, y: 26 },
        correctRotation: 0,
        size: 44,
        width: 44,
        height: 24,
      },
      // Keyboard base
      {
        id: 'base',
        type: 'rectangle',
        color: 'gray',
        correctPosition: { x: 15, y: 58 },
        correctRotation: 0,
        size: 70,
        width: 70,
        height: 18,
      },
    ],
  },
  {
    id: 'robot_fancy',
    nameEt: 'Robot',
    nameEn: 'Robot',
    category: 'objects',
    difficulty: 'hard',
    gridSize: 100,
    pieces: [
      {
        id: 'head',
        type: 'square',
        color: 'gray',
        correctPosition: { x: 35, y: 10 },
        correctRotation: 0,
        size: 30,
      },
      {
        id: 'eye_l',
        type: 'circle',
        color: 'cyan',
        correctPosition: { x: 40, y: 20 },
        correctRotation: 0,
        size: 10,
      },
      {
        id: 'eye_r',
        type: 'circle',
        color: 'cyan',
        correctPosition: { x: 55, y: 20 },
        correctRotation: 0,
        size: 10,
      },
      {
        id: 'body',
        type: 'square',
        color: 'blue',
        correctPosition: { x: 25, y: 40 },
        correctRotation: 0,
        size: 50,
      },
      {
        id: 'arm_l',
        type: 'rectangle',
        color: 'gray',
        correctPosition: { x: 7, y: 45 },
        correctRotation: 0,
        size: 42,
        width: 18,
        height: 42,
      },
      {
        id: 'arm_r',
        type: 'rectangle',
        color: 'gray',
        correctPosition: { x: 75, y: 45 },
        correctRotation: 0,
        size: 42,
        width: 18,
        height: 42,
      },
      {
        id: 'foot_l',
        type: 'rectangle',
        color: 'gray',
        correctPosition: { x: 25, y: 90 },
        correctRotation: 0,
        size: 25,
        width: 25,
        height: 10,
      },
      {
        id: 'foot_r',
        type: 'rectangle',
        color: 'gray',
        correctPosition: { x: 50, y: 90 },
        correctRotation: 0,
        size: 25,
        width: 25,
        height: 10,
      },
    ],
  },
];

export const SHAPE_SHIFT_PUZZLES_PACK: ContentPack<Puzzle> = {
  id: 'math.geometry_shapes.shape_shift_puzzles',
  skillId: MATH_GEOMETRY_SHAPES_SKILL.id,
  locale: 'et',
  version: '1.0.0',
  title: { et: 'Kujundite ladumise pusled', en: 'Shape Shift puzzles' },
  items: SHAPE_SHIFT_PUZZLES,
};
