import type { Theme, Category, GameConfig, MechanicConfig, ProfileType } from '../types/game';
import type { Profile } from '../types/profile';

export const APP_KEY = 'smart_adv_v45_pro';

export const THEME: Record<string, Theme> = {
  orange: {
    bg: 'bg-orange-50',
    border: 'border-orange-500',
    text: 'text-orange-600',
    iconBg: 'bg-orange-100',
    accent: 'bg-orange-500',
  },
  purple: {
    bg: 'bg-purple-50',
    border: 'border-purple-500',
    text: 'text-purple-600',
    iconBg: 'bg-purple-100',
    accent: 'bg-purple-500',
  },
  green: {
    bg: 'bg-green-50',
    border: 'border-green-500',
    text: 'text-green-600',
    iconBg: 'bg-green-100',
    accent: 'bg-green-500',
  },
  blue: {
    bg: 'bg-blue-50',
    border: 'border-blue-500',
    text: 'text-blue-600',
    iconBg: 'bg-blue-100',
    accent: 'bg-blue-500',
  },
  pink: {
    bg: 'bg-pink-50',
    border: 'border-pink-500',
    text: 'text-pink-600',
    iconBg: 'bg-pink-100',
    accent: 'bg-pink-500',
  },
  teal: {
    bg: 'bg-teal-50',
    border: 'border-teal-500',
    text: 'text-teal-600',
    iconBg: 'bg-teal-100',
    accent: 'bg-teal-500',
  },
  indigo: {
    bg: 'bg-indigo-50',
    border: 'border-indigo-500',
    text: 'text-indigo-600',
    iconBg: 'bg-indigo-100',
    accent: 'bg-indigo-500',
  },
};

export const CATEGORIES: Record<string, Category> = {
  language: {
    id: 'language',
    name: 'Language Games',
    emoji: '🔤',
    description: 'Words, letters and sentences',
    color: 'orange',
  },
  math: {
    id: 'math',
    name: 'Math',
    emoji: '🔢',
    description: 'Calculations and measurements',
    color: 'purple',
  },
  logic: {
    id: 'logic',
    name: 'Logic',
    emoji: '🧩',
    description: 'Patterns and programming',
    color: 'teal',
  },
  memory: {
    id: 'memory',
    name: 'Memory',
    emoji: '🧠',
    description: 'Memory games',
    color: 'blue',
  },
};

/**
 * Mechanics — one entry per shared engine/view. Bindings (GAME_CONFIG entries)
 * pointing at the same mechanic id collapse into one menu card; the card opens
 * a pack picker listing the bindings inside. New mechanics are added here when
 * a second binding starts sharing a view component.
 */
export const MECHANICS: Record<string, MechanicConfig> = {
  math_snake: {
    id: 'math_snake',
    title: 'NUMBRIMADU',
    desc: 'Söö õunu, lahenda tehe',
    theme: THEME.green!,
    icon: 'Sparkles',
    emoji: '🐍',
    category: 'math',
    allowedProfiles: ['starter', 'advanced'],
  },
};

// Paid hints: only add game-specific hints that give a real advantage in that game.
// Use the same system (GAME_CONFIG.paidHints, PaidHintButtons, stars/spendStars) for all.
export const GAME_CONFIG: Record<string, GameConfig> = {
  // 5+ games - simpler, visual (7 games - added letter_match)
  word_builder: {
    id: 'word_builder',
    title: 'WORD MASTER',
    theme: THEME.orange!,
    icon: 'FileText',
    emoji: '📝',
    desc: 'Build a word from letters',
    allowedProfiles: ['starter', 'advanced'],
    difficulty: 'easy',
    category: 'language',
    paidHints: [
      { id: 'reveal_next', icon: '🔤', cost: 1, labelKey: 'games.word_builder.hintRevealNextCost' },
      { id: 'eliminate', icon: '❌', cost: 1, labelKey: 'games.word_builder.hintEliminateCost' },
    ],
  },
  word_cascade: {
    id: 'word_cascade',
    title: 'WORD CASCADE',
    theme: THEME.pink!,
    icon: 'Layers',
    emoji: '🌊',
    desc: 'Catch letters and build words fast',
    allowedProfiles: ['starter', 'advanced'],
    difficulty: 'medium',
    category: 'language',
    paidHints: [
      { id: 'reveal_next', icon: '🔤', cost: 1, labelKey: 'games.word_cascade.hintRevealNextCost' },
    ],
  },
  syllable_builder: {
    id: 'syllable_builder',
    title: 'SYLLABLE MASTER',
    theme: THEME.orange!,
    icon: 'Layers',
    emoji: '📖',
    desc: 'Put syllables together into a word',
    allowedProfiles: ['starter'],
    difficulty: 'easy',
    category: 'language',
  },
  pattern: {
    id: 'pattern',
    title: 'PATTERN TRAIN',
    theme: THEME.teal!,
    icon: 'TrainFront',
    emoji: '🚂',
    desc: 'Continue the pattern',
    allowedProfiles: ['starter', 'advanced'],
    difficulty: 'easy',
    category: 'logic',
    paidHints: [
      { id: 'eliminate', icon: '❌', cost: 1, labelKey: 'games.pattern.hintEliminateCost' },
    ],
  },
  sentence_logic: {
    id: 'sentence_logic',
    title: 'SENTENCE DETECTIVE',
    theme: THEME.green!,
    icon: 'BookOpen',
    emoji: '🔍',
    desc: 'Where is the object?',
    allowedProfiles: ['starter', 'advanced'],
    difficulty: 'medium',
    category: 'language',
  },
  memory_math: {
    id: 'memory_math',
    title: 'MATH MEMORY',
    theme: THEME.green!,
    icon: 'Brain',
    emoji: '🧠',
    desc: 'Find the equation and answer',
    allowedProfiles: ['starter', 'advanced'],
    difficulty: 'medium',
    category: 'memory',
    paidHints: [
      { id: 'reveal_pair', icon: '👁️', cost: 1, labelKey: 'games.memory_math.hintRevealPairCost' },
    ],
  },
  picture_pairs: {
    id: 'picture_pairs',
    title: 'PICTURE PAIRS',
    theme: THEME.pink!,
    icon: 'Layers',
    emoji: '🖼️',
    desc: 'Match pictures and words',
    allowedProfiles: ['starter', 'advanced'],
    difficulty: 'easy',
    category: 'memory',
    paidHints: [
      {
        id: 'reveal_pair',
        icon: '👁️',
        cost: 1,
        labelKey: 'games.picture_pairs.hintRevealPairCost',
      },
    ],
  },
  robo_path: {
    id: 'robo_path',
    title: 'ROBO PATH',
    theme: THEME.indigo!,
    icon: 'Bot',
    emoji: '🤖',
    desc: 'Program the robot',
    allowedProfiles: ['starter', 'advanced'],
    difficulty: 'medium',
    category: 'logic',
  },
  addition_snake: {
    id: 'addition_snake',
    title: 'LIITMISUSS',
    theme: THEME.green!,
    icon: 'Plus',
    emoji: '➕',
    desc: 'Liitmine kuni 20',
    allowedProfiles: ['starter', 'advanced'],
    difficulty: 'easy',
    category: 'math',
    mechanic: 'math_snake',
    paidHints: [
      { id: 'eliminate', icon: '❌', cost: 1, labelKey: 'games.addition_snake.hintEliminateCost' },
    ],
    visualTheme: { snakePalette: 'emerald' },
  },
  addition_big_snake: {
    id: 'addition_big_snake',
    title: 'SUUR LIITMISUSS',
    theme: THEME.teal!,
    icon: 'Plus',
    emoji: '🧮',
    desc: 'Liitmine kuni 100',
    allowedProfiles: ['starter', 'advanced'],
    difficulty: 'medium',
    category: 'math',
    mechanic: 'math_snake',
    paidHints: [
      {
        id: 'eliminate',
        icon: '❌',
        cost: 1,
        labelKey: 'games.addition_big_snake.hintEliminateCost',
      },
    ],
    visualTheme: { snakePalette: 'teal' },
  },
  subtraction_snake: {
    id: 'subtraction_snake',
    title: 'LAHUTUSUSS',
    theme: THEME.orange!,
    icon: 'Minus',
    emoji: '➖',
    desc: 'Lahutamine kuni 20',
    allowedProfiles: ['starter', 'advanced'],
    difficulty: 'easy',
    category: 'math',
    mechanic: 'math_snake',
    paidHints: [
      {
        id: 'eliminate',
        icon: '❌',
        cost: 1,
        labelKey: 'games.subtraction_snake.hintEliminateCost',
      },
    ],
    visualTheme: { snakePalette: 'orange' },
  },
  subtraction_big_snake: {
    id: 'subtraction_big_snake',
    title: 'SUUR LAHUTUSUSS',
    theme: THEME.pink!,
    icon: 'Minus',
    emoji: '🧮',
    desc: 'Lahutamine kuni 100',
    allowedProfiles: ['starter', 'advanced'],
    difficulty: 'medium',
    category: 'math',
    mechanic: 'math_snake',
    paidHints: [
      {
        id: 'eliminate',
        icon: '❌',
        cost: 1,
        labelKey: 'games.subtraction_big_snake.hintEliminateCost',
      },
    ],
    visualTheme: { snakePalette: 'pink' },
  },
  multiplication_snake: {
    id: 'multiplication_snake',
    title: 'KORRUTUSUSS',
    theme: THEME.indigo!,
    icon: 'Sparkles',
    emoji: '🪐',
    desc: 'Korrutustabel 1–5',
    allowedProfiles: ['starter', 'advanced'],
    difficulty: 'medium',
    category: 'math',
    mechanic: 'math_snake',
    paidHints: [
      {
        id: 'eliminate',
        icon: '❌',
        cost: 1,
        labelKey: 'games.multiplication_snake.hintEliminateCost',
      },
    ],
    visualTheme: {
      normalCollectibleEmoji: '⭐',
      challengeCollectibleEmoji: '🪐',
      background: 'cosmic',
      snakePalette: 'indigo',
    },
  },
  multiplication_big_snake: {
    id: 'multiplication_big_snake',
    title: 'SUUR KORRUTUSUSS',
    theme: THEME.purple!,
    icon: 'Sparkles',
    emoji: '🌌',
    desc: 'Korrutustabel 1–10',
    allowedProfiles: ['starter', 'advanced'],
    difficulty: 'hard',
    category: 'math',
    mechanic: 'math_snake',
    paidHints: [
      {
        id: 'eliminate',
        icon: '❌',
        cost: 1,
        labelKey: 'games.multiplication_big_snake.hintEliminateCost',
      },
    ],
    visualTheme: {
      normalCollectibleEmoji: '✨',
      challengeCollectibleEmoji: '🌌',
      background: 'cosmic',
      snakePalette: 'purple',
    },
  },
  letter_match: {
    id: 'letter_match',
    title: 'LETTER DETECTIVE',
    theme: THEME.pink!,
    icon: 'Search',
    emoji: '🔤',
    desc: 'Find the correct letter',
    allowedProfiles: ['starter', 'advanced'],
    difficulty: 'easy',
    category: 'language',
  },
  unit_conversion: {
    id: 'unit_conversion',
    title: 'UNITS',
    theme: THEME.blue!,
    icon: 'Ruler',
    emoji: '📐',
    desc: 'Convert units',
    allowedProfiles: ['starter', 'advanced'],
    difficulty: 'medium',
    category: 'math',
    paidHints: [
      { id: 'eliminate', icon: '❌', cost: 1, labelKey: 'games.unit_conversion.hintEliminateCost' },
    ],
  },
  compare_sizes: {
    id: 'compare_sizes',
    title: 'NUMBER COMPARE',
    theme: THEME.indigo!,
    icon: 'Hash',
    emoji: '⚖️',
    desc: 'Compare numbers',
    allowedProfiles: ['starter', 'advanced'],
    difficulty: 'easy',
    category: 'math',
    paidHints: [
      { id: 'eliminate', icon: '❌', cost: 1, labelKey: 'games.compare_sizes.hintEliminateCost' },
    ],
  },
  star_mapper: {
    id: 'star_mapper',
    title: 'STAR MAPPER',
    theme: THEME.indigo!,
    icon: 'Star',
    emoji: '⭐',
    desc: 'Learn the constellations',
    allowedProfiles: ['starter', 'advanced'],
    difficulty: 'medium',
    category: 'logic',
    paidHints: [
      { id: 'guide', icon: '💡', cost: 1, labelKey: 'games.star_mapper.hintGuideCost' },
      { id: 'connect', icon: '✨', cost: 2, labelKey: 'games.star_mapper.hintConnectCost' },
    ],
  },
  shape_shift: {
    id: 'shape_shift',
    title: 'SHAPE SHIFT',
    theme: THEME.teal!,
    icon: 'Shapes',
    emoji: '🧩',
    desc: 'Build shapes from pieces',
    allowedProfiles: ['starter', 'advanced'],
    difficulty: 'easy',
    category: 'logic',
    paidHints: [
      { id: 'outline', icon: '👁️', cost: 1, labelKey: 'games.shape_shift.hintOutlineCost' },
      { id: 'place', icon: '🧩', cost: 2, labelKey: 'games.shape_shift.hintPlacePieceCost' },
    ],
  },
  battlelearn: {
    id: 'battlelearn',
    title: 'BATTLELEARN',
    theme: THEME.blue!,
    icon: 'Anchor',
    emoji: '⚓',
    desc: 'Answer and sink ships',
    allowedProfiles: ['starter', 'advanced'],
    difficulty: 'medium',
    category: 'math',
    levelUpStrategy: 'onGameWin',
    paidHints: [
      {
        id: 'reveal_empty',
        icon: '💧',
        cost: 1,
        labelKey: 'games.battlelearn.hintRevealEmptyCost',
      },
      { id: 'reveal', icon: '🎯', cost: 10, labelKey: 'games.battlelearn.hintRevealCost' },
      { id: 'eliminate', icon: '❌', cost: 1, labelKey: 'games.battlelearn.hintEliminateCost' },
    ],
  },
  shape_dash: {
    id: 'shape_dash',
    title: 'SHAPE DASH',
    theme: THEME.teal!,
    icon: 'Gamepad2',
    emoji: '🏃',
    desc: 'Jump, dodge, and answer geometry',
    allowedProfiles: ['starter', 'advanced'],
    difficulty: 'medium',
    category: 'logic',
    paidHints: [
      { id: 'reveal_gate', icon: '🎯', cost: 2, labelKey: 'games.shape_dash.hintRevealGateCost' },
      { id: 'slow_time', icon: '⏱️', cost: 3, labelKey: 'games.shape_dash.hintSlowTimeCost' },
    ],
  },
  // Advanced-only games (7+)
  balance_scale: {
    id: 'balance_scale',
    title: 'SCALES',
    theme: THEME.blue!,
    icon: 'Scale',
    emoji: '⚖️',
    desc: 'Balance the scales',
    allowedProfiles: ['advanced'],
    difficulty: 'hard',
    category: 'math',
    paidHints: [
      { id: 'eliminate', icon: '❌', cost: 1, labelKey: 'games.balance_scale.hintEliminateCost' },
    ],
  },
  time_match: {
    id: 'time_match',
    title: 'CLOCK GAME',
    theme: THEME.blue!,
    icon: 'Clock3',
    emoji: '🕐',
    desc: 'Set the time',
    allowedProfiles: ['advanced'],
    difficulty: 'hard',
    category: 'math',
    paidHints: [
      { id: 'eliminate', icon: '❌', cost: 1, labelKey: 'games.time_match.hintEliminateCost' },
    ],
  },
};

// Profiles are extensible with difficulty offset
export const PROFILES: Record<ProfileType, Profile> = {
  starter: {
    id: 'starter',
    label: '5+',
    desc: 'Preschooler',
    levelStart: 1,
    difficultyOffset: 0,
    emoji: '👧',
  },
  advanced: {
    id: 'advanced',
    label: '7+',
    desc: 'School child',
    levelStart: 3,
    difficultyOffset: 2,
    emoji: '🧒',
  },
};

export const ICONS: Record<string, string> = {
  Type: 'Type',
  Brain: 'Brain',
  BookOpen: 'BookOpen',
  Scale: 'Scale',
  GraduationCap: 'GraduationCap',
  TrainFront: 'TrainFront',
  Bot: 'Bot',
  Clock3: 'Clock3',
  Ruler: 'Ruler',
  Gamepad2: 'Gamepad2',
  Hash: 'Hash',
  FileText: 'FileText',
  Layers: 'Layers',
  Search: 'Search',
  Star: 'Star',
  Shapes: 'Shapes',
  Target: 'Target',
};
