export interface SyllableWord {
  syllables: string[];
  emoji: string;
}

export const SYLLABLE_WORDS: Record<'et' | 'en', SyllableWord[]> = {
  et: [
    // 2 syllables
    { syllables: ['AU', 'TO'], emoji: '🚗' },
    { syllables: ['KA', 'LA'], emoji: '🐟' },
    { syllables: ['KO', 'ER'], emoji: '🐶' },
    { syllables: ['KA', 'RU'], emoji: '🐻' },
    { syllables: ['LU', 'MI'], emoji: '❄️' },
    { syllables: ['MA', 'JA'], emoji: '🏠' },
    { syllables: ['HE', 'LI'], emoji: '🔔' },
    { syllables: ['MA', 'RI'], emoji: '🍓' },
    { syllables: ['KO', 'DU'], emoji: '🏡' },
    { syllables: ['JÕ', 'GI'], emoji: '🏞️' },
    { syllables: ['ME', 'RI'], emoji: '🌊' },
    { syllables: ['E', 'MA'], emoji: '👩' },
    { syllables: ['I', 'SA'], emoji: '👨' },
    { syllables: ['JÄ', 'NES'], emoji: '🐰' },
    { syllables: ['RAA', 'MAT'], emoji: '📖' },
    { syllables: ['RO', 'BOT'], emoji: '🤖' },
    { syllables: ['POR', 'GAND'], emoji: '🥕' },
    { syllables: ['KAR', 'TUL'], emoji: '🥔' },
    { syllables: ['TO', 'MAT'], emoji: '🍅' },
    { syllables: ['JÄÄ', 'TIS'], emoji: '🍦' },
    { syllables: ['KÜP', 'SIS'], emoji: '🍪' },
    { syllables: ['LEN', 'NUK'], emoji: '✈️' },
    { syllables: ['KIR', 'SI'], emoji: '🍒' },
    { syllables: ['SID', 'RUN'], emoji: '🍋' },
    { syllables: ['PÄH', 'KEL'], emoji: '🌰' },
    { syllables: ['PI', 'TSA'], emoji: '🍕' },
    { syllables: ['AR', 'BUUS'], emoji: '🍉' },
    { syllables: ['A', 'KEN'], emoji: '🪟' },
    { syllables: ['PA', 'BER'], emoji: '📄' },
    { syllables: ['PEE', 'GEL'], emoji: '🪞' },
    { syllables: ['SÕ', 'BER'], emoji: '🤝' },
    { syllables: ['PÄI', 'KE'], emoji: '☀️' },

    // 3 syllables
    { syllables: ['HO', 'BU', 'NE'], emoji: '🐎' },
    { syllables: ['E', 'LE', 'VANT'], emoji: '🐘' },
    { syllables: ['RE', 'BA', 'NE'], emoji: '🦊' },
    { syllables: ['LU', 'SI', 'KAS'], emoji: '🥄' },
    { syllables: ['LI', 'BLI', 'KAS'], emoji: '🦋' },
    { syllables: ['A', 'NA', 'NASS'], emoji: '🍍' },
    { syllables: ['MAA', 'SI', 'KAS'], emoji: '🍓' },
    { syllables: ['MUU', 'SI', 'KA'], emoji: '🎼' },
    { syllables: ['AR', 'VU', 'TI'], emoji: '💻' },
    { syllables: ['TE', 'LE', 'FON'], emoji: '📱' },
    { syllables: ['PO', 'LI', 'TSEI'], emoji: '👮' },
    { syllables: ['KA', 'ME', 'RA'], emoji: '📷' },

    // 4 syllables
    { syllables: ['HE', 'LI', 'KOP', 'TER'], emoji: '🚁' },
    { syllables: ['KA', 'EL', 'KIR', 'JAK'], emoji: '🦒' },
    { syllables: ['LU', 'ME', 'SA', 'DU'], emoji: '❄️' },
    { syllables: ['VIH', 'MA', 'VA', 'RI'], emoji: '☂️' },
    { syllables: ['MO', 'TOOR', 'RA', 'TAS'], emoji: '🏍️' },
    { syllables: ['VA', 'NA', 'E', 'MA'], emoji: '👵' },
    { syllables: ['VA', 'NA', 'I', 'SA'], emoji: '👴' },
  ],
  en: [
    // 2 syllables
    { syllables: ['AP', 'PLE'], emoji: '🍎' },
    { syllables: ['TA', 'BLE'], emoji: '🪑' },
    { syllables: ['TI', 'GER'], emoji: '🐯' },
    { syllables: ['LI', 'ON'], emoji: '🦁' },
    { syllables: ['ZE', 'BRA'], emoji: '🦓' },
    { syllables: ['PIZ', 'ZA'], emoji: '🍕' },
    { syllables: ['BUR', 'GER'], emoji: '🍔' },
    { syllables: ['RAB', 'BIT'], emoji: '🐰' },
    { syllables: ['TUR', 'TLE'], emoji: '🐢' },
    { syllables: ['MON', 'KEY'], emoji: '🐵' },
    { syllables: ['PEN', 'CIL'], emoji: '✏️' },
    { syllables: ['FLOW', 'ER'], emoji: '🌸' },
    { syllables: ['WIN', 'TER'], emoji: '❄️' },
    { syllables: ['SUM', 'MER'], emoji: '☀️' },
    { syllables: ['RO', 'BOT'], emoji: '🤖' },
    { syllables: ['PIC', 'NIC'], emoji: '🧺' },
    { syllables: ['O', 'CEAN'], emoji: '🌊' },
    { syllables: ['BUT', 'TER'], emoji: '🧈' },
    { syllables: ['CAR', 'ROT'], emoji: '🥕' },
    { syllables: ['GAR', 'DEN'], emoji: '🌻' },

    // 3 syllables
    { syllables: ['BA', 'NA', 'NA'], emoji: '🍌' },
    { syllables: ['EL', 'E', 'PHANT'], emoji: '🐘' },
    { syllables: ['OC', 'TO', 'PUS'], emoji: '🐙' },
    { syllables: ['PO', 'TA', 'TO'], emoji: '🥔' },
    { syllables: ['TO', 'MA', 'TO'], emoji: '🍅' },
    { syllables: ['BUT', 'TER', 'FLY'], emoji: '🦋' },
    { syllables: ['COM', 'PU', 'TER'], emoji: '💻' },
    { syllables: ['TE', 'LE', 'PHONE'], emoji: '📱' },
    { syllables: ['UM', 'BREL', 'LA'], emoji: '☂️' },
    { syllables: ['CAM', 'ER', 'A'], emoji: '📷' },
    { syllables: ['AN', 'I', 'MAL'], emoji: '🐾' },
    { syllables: ['CHOC', 'O', 'LATE'], emoji: '🍫' },

    // 4 syllables
    { syllables: ['A', 'VO', 'CA', 'DO'], emoji: '🥑' },
    { syllables: ['WA', 'TER', 'MEL', 'ON'], emoji: '🍉' },
    { syllables: ['HE', 'LI', 'COP', 'TER'], emoji: '🚁' },
  ],
};
